symbols:
- '2330'
- '2317'
- '2454'
- '2303'
- '2308'
- '2412'
- '2882'
- '2881'
- '1301'
- '1303'
- '3034'
- '3711'
- '3481'
- '5880'
- '2379'
- '77868'
- '77798'
- '77866'
- '6403'
- '3595'
market:
  tz: Asia/Taipei
  start: 08:55
  end: '13:35'
  poll_seconds: 10
  batch_size: 40
strategy:
  ema_fast: 5
  ema_slow: 20
  rsi_period: 14
  buy_rsi_min: 50
  sell_rsi_max: 45
  cooldown_minutes: 5
  min_bars_for_signal: 20
  take_profit_pct: 0.03
  stop_loss_pct: 0.015
trading:
  position_size_shares: 1
  allow_multi_entry: false
  carry_position_overnight: true
notify:
  mode: gas
  line_token_env: LINE_NOTIFY_TOKEN
  discord_webhook_env: DISCORD_WEBHOOK_URL
  generic_webhook_env: N8N_WEBHOOK_URL
  gas_webhook_env: GAS_WEBHOOK_URL
  gas_secret_env: GAS_SECRET
